services:
  backend:
    container_name: hsl-backend
    build:
      context: ./backend
      target: development
    ports: 
      - 4000:4000
    environment:
      - GRAPHQL_API_TOKEN=${GRAPHQL_API_TOKEN}
      - GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT}
      - GEOCODING_ENDPOINT=${GEOCODING_ENDPOINT}
    restart: always
    volumes:
      - ./backend:/app
    networks:
      - hsl-network

  frontend:
    container_name: hsl-frontend
    build: 
      context: ./frontend
      target: development
      args:
        - GRAPHQL_API_TOKEN=${GRAPHQL_API_TOKEN}
        - GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT}
        - VITE_HOST=${VITE_HOST}
    ports: 
      - 5173:5173
    environment:
      - VITE_HOST=${VITE_HOST}
      - GRAPHQL_API_TOKEN=${GRAPHQL_API_TOKEN}
      - GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT}
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hsl-network

networks:
  hsl-network:
    name: hsl-network
    driver: bridge