query alerts {
  alerts {
    alertCause
    alertDescriptionText(language: "en")
    effectiveEndDate
    effectiveStartDate
    entities {
      ... on Route {
        id
        longName(language: "en")
        shortName
        stops {
          name(language: "en")
          code
          routes {
            longName(language: "en")
            shortName
          }
        }
      }
    }
  }
}
