query nearest {
  nearest(lat: 60.1699, lon: 24.9384) {
    edges {
      node {
        place {
          lon
          lat
          ... on BikePark {
            id
            name
            lat
            lon
            tags
          }
          ... on BikeRentalStation {
            id
            name
            lat
            lon
            capacity
            bikesAvailable
          }
          ... on Stop {
            id
            name
            lat
            lon
            code
            desc(language: "en")
          }
        }
        distance
        id
      }
    }
  }
}
