# An ISO-8601-formatted datetime with offset, i.e. 2023-06-13T14:30+03:00 for 2:30pm on June 13th 2023 at Helsinki's offset from UTC at that time.

# ISO-8601 allows many different formats but OTP will only return the profile specified in RFC3339.


# Duration
# Duration in a lenient ISO-8601 duration format. Example P2DT2H12M40S, 2d2h12m40s or 1h

query planConnection($originLat: CoordinateValue!, $originLon: CoordinateValue!, $destinationLat: CoordinateValue!, $destinationLon: CoordinateValue!, $planTransitModePreferenceInput: [PlanTransitModePreferenceInput!]) {
  planConnection(
    origin: {location: {coordinate: {latitude: $originLat, longitude: $originLon}}}
    destination: {location: {coordinate: {latitude: $destinationLat, longitude: $destinationLon}}}
    searchWindow: "PT5H"
    modes: {transit: {transit: $planTransitModePreferenceInput}}
  ) {
    edges {
      node {
        elevationLost
        elevationGained
        duration
        emissionsPerPerson {
          co2
        }
        walkDistance
        walkTime
        legs {
          id
          duration
          mode
          distance
          start {
            scheduledTime
          }
          end {
            scheduledTime
          }
          realtimeState
          legGeometry {
            length
            points
          }
          from {
            stop {
              lon
              name(language: "en")
              code
              lat
              vehicleMode
            }
            departure {
              scheduledTime
            }
          }
          to {
            stop {
              name
              code
              lat
              lon
              vehicleMode
            }
            departure {
              scheduledTime
            }
          }
          intermediateStops {
            code
            desc(language: "en")
            lat
            lon
            name(language: "en")
          }
          route {
            longName(language: "en")
            shortName
          }
        }
        waitingTime
        start
        numberOfTransfers
        generalizedCost
        end
      }
    }
  }
}
