query rentalVehicles {
  rentalVehicles(formFactors: SCOOTER) {
    allowPickupNow
    id
    lat
    lon
    name
    operative
    vehicleId
    rentalNetwork {
      networkId
      url
    }
    rentalUris {
      android
      ios
      web
    }
    vehicleType {
      formFactor
      propulsionType
    }
  }
}
